Repository boostcampwm-2022/web36-Japari, pull requests merged in 2022-11, with the labels that each got.

#5 [FE] 랜딩 페이지 UI 구현
  .eslintrc.js
  .prettierrc
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/landing-image.png
  client/public/logo/Ja-Party-word.png
  client/public/logo/github_logo.png
  client/public/logo/google_logo.png
  client/public/logo/japari-logo-image.svg
  client/public/logo/japari-logo-word.svg
  client/public/logo/kakao_logo.png
  client/public/logo/naver_logo.png
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/src/App.tsx
  client/src/components/Button/index.stories.tsx
  client/src/components/Button/index.tsx
  client/src/components/Button/styles.tsx
  client/src/components/Logo/index.stories.tsx
  client/src/components/Logo/index.tsx
  client/src/components/Logo/styles.tsx
  client/src/pages/landing/index.tsx
  client/src/pages/landing/style.ts
  client/src/stories/Header.tsx
  client/src/stories/Page.tsx
  client/tsconfig.json
Labels: frontend

#11 [FE] 공통 컴포넌트 부분 구현
  client/src/components/Button/styles.ts
  client/src/components/CheckBox/checkbox.stories.tsx
  client/src/components/CheckBox/index.tsx
  client/src/components/CheckBox/styles.ts
  client/src/components/Input/index.tsx
  client/src/components/Input/input.stories.tsx
  client/src/components/Input/styles.ts
  client/src/components/Logo/styles.ts
  client/src/components/Select/index.tsx
  client/src/components/Select/select.stories.tsx
  client/src/components/Select/styles.ts
Labels: frontend

#12 [FE] 캠 관련 컴포넌트 구현
  client/.storybook/preview.js
  client/src/components/Button/styles.ts
  client/src/components/Cam/index.stories.tsx
  client/src/components/Cam/index.tsx
  client/src/components/Cam/styles.ts
  client/src/components/CheckBox/styles.ts
  client/src/components/InGameCamList/index.stories.tsx
  client/src/components/InGameCamList/index.tsx
  client/src/components/InGameCamList/styles.ts
  client/src/components/RoomList/RoomRecord/index.stories.tsx
  client/src/components/RoomList/RoomRecord/styles.ts
  client/src/components/RoomList/index.stories.tsx
  client/src/components/RoomList/index.tsx
  client/src/components/RoomList/styles.ts
  client/src/components/Select/styles.ts
  client/src/components/WaitingRoomInfo/index.stories.tsx
  client/src/components/WaitingRoomInfo/index.tsx
  client/src/components/WaitingRoomInfo/styles.ts
  client/src/index.tsx
  client/src/styles/global.ts
  client/src/styles/theme.ts
Labels: frontend

#13 [FE] 유저 목록 사이드바 UI 구현
  client/src/assets/images/default-user-image.png
  client/src/components/UserList/UserListTab/index.tsx
  client/src/components/UserList/UserListTab/styles.ts
  client/src/components/UserList/UserTable/UserRecord/index.tsx
  client/src/components/UserList/UserTable/UserRecord/styles.ts
  client/src/components/UserList/UserTable/index.tsx
  client/src/components/UserList/UserTable/styles.ts
  client/src/components/UserList/index.stories.tsx
  client/src/components/UserList/index.tsx
  client/src/components/UserList/styles.ts
Labels: frontend

#19 [FE] 헤더 컴포넌트 구현
  client/src/assets/icons/cam-off.svg
  client/src/assets/icons/cam-on.svg
  client/src/assets/icons/logout-icon.svg
  client/src/assets/icons/mic-off.svg
  client/src/assets/icons/mic-on.svg
  client/src/components/Button/index.tsx
  client/src/components/Header/Header.stories.tsx
  client/src/components/Header/Logout/index.stories.tsx
  client/src/components/Header/Logout/index.tsx
  client/src/components/Header/Logout/styles.ts
  client/src/components/Header/StatusMicCam/index.stories.tsx
  client/src/components/Header/StatusMicCam/index.tsx
  client/src/components/Header/StatusMicCam/styles.ts
  client/src/components/Header/header.css
  client/src/components/Header/index.stories.tsx
  client/src/components/Header/index.tsx
  client/src/components/Header/styles.ts
  client/src/components/Logo/index.tsx
  client/src/components/Page/index.stories.tsx
  client/src/components/Page/index.tsx
Labels: frontend

#20 [FE] 프로필 컴포넌트 UI 구현
  client/src/assets/icons/edit-icon.svg
  client/src/components/Profile/ProfileContent/index.tsx
  client/src/components/Profile/ProfileContent/styles.ts
  client/src/components/Profile/index.stories.tsx
  client/src/components/Profile/index.tsx
  client/src/components/Profile/styles.ts
Labels: frontend

#23 feat: 🎸 채팅 컴포넌트 개발
  client/src/assets/icons/chat-input-enter.svg
  client/src/components/Chatting/ChatInput/index.stories.tsx
  client/src/components/Chatting/ChatInput/index.tsx
  client/src/components/Chatting/ChatInput/styles.ts
  client/src/components/Chatting/ChatLog/index.stories.tsx
  client/src/components/Chatting/ChatLog/index.tsx
  client/src/components/Chatting/ChatLog/styles.ts
  client/src/components/Chatting/index.stories.tsx
  client/src/components/Chatting/index.tsx
  client/src/components/Chatting/styles.ts
Labels: frontend

#28 [FE] 공통 컴포넌트
  client/src/@types/dto.d.ts
  client/src/components/Chatting/ChatInput/index.tsx
  client/src/components/Input/index.tsx
  client/src/components/Input/input.stories.tsx
  client/src/components/Input/styles.ts
  client/src/components/Modal/FriendRequest/index.tsx
  client/src/components/Modal/FriendRequest/styles.ts
  client/src/components/Modal/GameInvitation/index.tsx
  client/src/components/Modal/GameInvitation/styles.ts
  client/src/components/Modal/NickNameSetting/index.tsx
  client/src/components/Modal/PasswordSetting/index.tsx
  client/src/components/Modal/PasswordSetting/styles.ts
  client/src/components/Modal/RoomSetting/index.tsx
  client/src/components/Modal/RoomSetting/styles.ts
  client/src/components/Modal/index.stories.tsx
  client/src/components/Modal/index.tsx
  client/src/components/Modal/styles.ts
  client/src/components/Profile/ProfileContent/index.tsx
  client/src/components/Profile/ProfileContent/styles.ts
  client/src/components/Profile/index.stories.tsx
  client/src/components/Profile/index.tsx
  client/src/components/Profile/styles.ts
  client/src/components/RoomList/index.tsx
  client/src/components/Select/index.tsx
  client/src/components/Select/select.stories.tsx
  client/src/components/Select/styles.ts
Labels: frontend

#27 [FE] 로비페이지 레이아웃
  client/src/App.tsx
  client/src/components/Page/index.tsx
  client/src/components/Page/page.css
  client/src/components/Page/styles.tsx
  client/src/components/RoomList/RoomRecord/styles.ts
  client/src/components/RoomList/styles.ts
  client/src/components/UserList/UserTable/styles.ts
  client/src/pages/landing/index.tsx
  client/src/pages/landing/styles.ts
  client/src/pages/lobby/dummy.ts
  client/src/pages/lobby/index.tsx
  client/src/pages/lobby/styles.ts
Labels: frontend

#30 [FE] 랜딩페이지 레이아웃
  client/src/components/Header/index.tsx
  client/src/components/Header/styles.ts
  client/src/components/Page/index.stories.tsx
  client/src/pages/landing/index.tsx
Labels: frontend

#33 [FE] 인게임 페이지 레이아웃
  client/src/App.tsx
  client/src/components/InGameCamList/index.tsx
  client/src/components/InGameCamList/styles.ts
  client/src/pages/dummy.ts
  client/src/pages/landing/styles.ts
  client/src/pages/lobby/index.tsx
  client/src/pages/lobby/styles.ts
  client/src/pages/playing/index.tsx
  client/src/pages/playing/styles.ts
  client/src/pages/waiting/index.tsx
  client/src/pages/waiting/styles.ts
Labels: frontend

#35 [FE] URL에 따른 headerType 동적 변환
  client/src/components/Page/index.tsx
  client/src/components/Page/styles.ts
Labels: frontend

#39 [BE] 토큰 전송 및 리다이렉션
  server/package-lock.json
  server/package.json
  server/prisma/migrations/20221124031435_/migration.sql
  server/prisma/schema.prisma
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/auth/github.service.ts
  server/src/auth/jwt-access-token.guard.ts
  server/src/auth/jwt-access-token.strategy.ts
  server/src/auth/jwt-refresh-token.guard.ts
  server/src/auth/jwt-refresh-token.strategy.ts
  server/src/main.ts
Labels: backend

#40 [FE] 컴포넌트간 navigate, 모달 open/close, select 컴포넌트 수정
  client/.storybook/preview.js
  client/public/index.html
  client/src/components/Cam/index.tsx
  client/src/components/Cam/styles.ts
  client/src/components/Modal/GameInvitation/index.tsx
  client/src/components/Modal/GameInvitation/styles.ts
  client/src/components/Modal/RoomSetting/index.tsx
  client/src/components/Modal/RoomSetting/styles.ts
  client/src/components/Modal/index.stories.tsx
  client/src/components/Modal/index.tsx
  client/src/components/Modal/styles.ts
  client/src/components/RoomList/RoomRecord/index.tsx
  client/src/components/RoomList/RoomRecord/styles.ts
  client/src/components/RoomList/index.stories.tsx
  client/src/components/RoomList/index.tsx
  client/src/components/Select/index.tsx
  client/src/components/WaitingRoomInfo/index.stories.tsx
  client/src/components/WaitingRoomInfo/index.tsx
  client/src/index.tsx
  client/src/pages/dummy.ts
Labels: frontend

#41 [FE] Input 컴포넌트 setValue 연결
  client/src/components/Chatting/ChatInput/index.tsx
  client/src/components/Input/index.tsx
  client/src/components/Input/input.stories.tsx
  client/src/components/Input/styles.ts
  client/src/components/Modal/NickNameSetting/index.tsx
  client/src/components/Modal/PasswordSetting/index.tsx
  client/src/components/Modal/RoomSetting/index.tsx
Labels: frontend

#43 [BE] DB에서 게임정보를 가져오는 API 작성
  server/src/app.module.ts
  server/src/game/game.controller.ts
  server/src/game/game.module.ts
  server/src/game/game.service.ts
Labels: backend

#50 [BE] 리팩토링 / Nest.js config 적용 / 소켓 연결
  server/package-lock.json
  server/package.json
  server/prisma/schema.prisma
  server/redis/game.ts
  server/redis/user.ts
  server/src/@types/express.d.ts
  server/src/app.controller.spec.ts
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/game/game.controller.ts
  server/src/game/game.service.ts
  server/src/main.ts
  server/src/modules/auth/auth.controller.ts
  server/src/modules/auth/auth.module.ts
  server/src/modules/auth/auth.service.ts
  server/src/modules/auth/github.service.ts
  server/src/modules/chat/chat.gateway.ts
  server/src/modules/chat/chat.module.ts
  server/src/modules/game/game.controller.ts
  server/src/modules/game/game.module.ts
  server/src/modules/game/game.service.ts
  server/src/modules/jwt/jwt-access-token.guard.ts
  server/src/modules/jwt/jwt-access-token.strategy.ts
  server/src/modules/jwt/jwt-refresh-token.guard.ts
  server/src/modules/jwt/jwt-refresh-token.strategy.ts
  server/src/modules/jwt/jwt.module.ts
  server/src/modules/prisma/prisma.module.ts
  server/src/modules/prisma/prisma.service.ts
  server/src/modules/redis/redis.module.ts
Labels: backend

#51 [FE] client에서의 채팅 기능 로직 작성
  client/src/components/Chatting/ChatInput/index.stories.tsx
  client/src/components/Chatting/ChatInput/index.tsx
  client/src/components/Chatting/ChatLog/index.tsx
  client/src/components/Chatting/index.tsx
  client/src/components/Input/index.tsx
Labels: frontend

#53 [BE] app gateway 구현, redis를 이용한 socket id - user email 바인딩, 포트 번호 변경
  server/src/app.gateway.ts
  server/src/app.module.ts
  server/src/main.ts
  server/src/modules/chat/chat.gateway.ts
  server/src/modules/chat/chat.module.ts
Labels: backend

#54 [BE] config 변경으로 인한 문제 해결
  client/src/setupProxy.js
  server/src/app.gateway.ts
  server/src/modules/auth/auth.controller.ts
  server/src/modules/chat/chat.gateway.ts
Labels: bug, backend

#55 [BE] 유저 정보 조회, 수정 api
  server/src/app.module.ts
  server/src/modules/user/user.controller.ts
  server/src/modules/user/user.module.ts
  server/src/modules/user/user.service.ts
Labels: backend

#57 [FE / BE] 로그인한 유저 정보 조회 API, 닉네임 설정 기능
  client/src/api/user.ts
  client/src/components/Input/index.tsx
  client/src/components/Modal/NickNameSetting/index.tsx
  client/src/components/Modal/index.tsx
  client/src/index.tsx
  client/src/pages/lobby/index.tsx
  client/src/recoil/user.ts
  server/src/modules/user/user.controller.ts
Labels: frontend, backend

#58 [BE] 소켓 이벤트 바인딩
  server/package-lock.json
  server/package.json
  server/src/app.controller.ts
  server/src/app.gateway.ts
  server/src/app.module.ts
  server/src/constants/redis-table-name.ts
  server/src/modules/auth/auth.service.ts
  server/src/modules/chat/chat.gateway.ts
  server/src/modules/chat/chat.module.ts
  server/src/modules/game-room/game-room.controller.ts
  server/src/modules/game-room/game-room.gateway.ts
  server/src/modules/game-room/game-room.module.ts
  server/src/modules/game-room/game-room.service.ts
  server/src/modules/user/user.controller.ts
  server/src/modules/user/user.gateway.ts
  server/src/modules/user/user.module.ts
  server/src/modules/user/user.service.ts
  server/util/convert.ts
  server/util/socket.ts
Labels: backend

#63 [BE] API 구현
  server/src/app.gateway.ts
  server/src/modules/chat/chat.gateway.ts
  server/src/modules/game-room/game-room.controller.ts
  server/src/modules/game-room/game-room.gateway.ts
  server/src/modules/game/game.controller.ts
  server/src/modules/user/user.controller.ts
  server/src/modules/user/user.gateway.ts
  server/src/modules/user/user.service.ts
Labels: backend

#62 [FE] 로딩 스피너 구현
  client/package-lock.json
  client/package.json
  client/src/components/Spinner/index.stories.tsx
  client/src/components/Spinner/index.tsx
  client/src/components/Spinner/styles.ts
Labels: frontend

#65 [FE] 커스텀 스크롤바 구현
  client/src/components/Chatting/ChatLog/styles.ts
  client/src/components/RoomList/styles.ts
  client/src/components/UserList/UserTable/styles.ts
  client/src/styles/global.ts
Labels: frontend

#67 [FE] 소켓 전역 관리를 위한 recoil 적용 및 Hook 개발
  client/package-lock.json
  client/package.json
  client/src/components/Chatting/ChatInput/index.stories.tsx
  client/src/components/Chatting/ChatInput/index.tsx
  client/src/components/Chatting/index.tsx
  client/src/hooks/useSocket.ts
  client/src/pages/lobby/index.tsx
  client/src/store/socket.ts
  package-lock.json
  package.json
  server/src/app.gateway.ts
  server/src/modules/auth/auth.service.ts
  server/src/modules/chat/chat.gateway.ts
  server/src/modules/game-room/game-room.gateway.ts
  server/src/modules/game-room/game-room.module.ts
Labels: frontend

#68 [FE] 프로필 컴포넌트에 user 정보 전달
  client/public/profile/default.png
  client/src/components/Loader/Spinner/index.tsx
  client/src/components/Loader/index.stories.tsx
  client/src/components/Loader/index.tsx
  client/src/components/Loader/styles.ts
  client/src/components/Profile/index.tsx
  client/src/components/Spinner/index.stories.tsx
  client/src/components/Spinner/index.tsx
  client/src/pages/lobby/index.tsx
  client/src/pages/waiting/index.tsx
  client/src/store/user.ts
  server/prisma/schema.prisma
Labels: frontend

#69 [FE] 로그아웃 구현
  client/src/api/auth.ts
  client/src/components/Header/Logout/index.tsx
  client/src/pages/landing/index.tsx
Labels: frontend

#71 [BE] API, 소켓 이벤트 검증 및 소켓 에러 처리
  server/package-lock.json
  server/package.json
  server/src/@types/express.d.ts
  server/src/constants/exception.ts
  server/src/exception-filters/websocket.filter.ts
  server/src/modules/auth/auth.controller.ts
  server/src/modules/auth/auth.service.ts
  server/src/modules/chat/chat.dto.ts
  server/src/modules/chat/chat.gateway.ts
  server/src/modules/game-room/dto/room-credential.dto.ts
  server/src/modules/game-room/dto/room-setting.dto.ts
  server/src/modules/game-room/game-room.gateway.ts
  server/src/modules/game/game.controller.ts
  server/src/modules/user/dto/new-nickname.dto.ts
  server/src/modules/user/dto/new-profile-image.dto.ts
  server/src/modules/user/user.controller.ts
Labels: backend

#72 [FE / BE] 게임방에 대한 소켓 이벤트
  client/src/api/gameRoom.ts
  client/src/api/user.ts
  client/src/components/Modal/RoomSetting/index.tsx
  client/src/components/RoomList/index.stories.tsx
  client/src/components/RoomList/index.tsx
  client/src/components/WaitingRoomInfo/index.stories.tsx
  client/src/components/WaitingRoomInfo/index.tsx
  client/src/pages/dummy.ts
  client/src/pages/lobby/index.tsx
  client/src/pages/waiting/index.tsx
  server/src/modules/game-room/game-room.controller.ts
  server/src/modules/game-room/game-room.gateway.ts
  server/src/modules/game-room/game-room.service.ts
Labels: frontend, backend

#74 [BE] 소켓 연결이 끊길 때 유저 퇴장 정보가 브로드캐스트 되지 않는 버그 수정
  server/src/app.gateway.ts
  server/src/modules/game-room/game-room.gateway.ts
  server/util/socket.ts
Labels: bug, backend

#76 [FE] URL에 따른 소켓 채널 변경
  client/src/components/Chatting/ChatInput/index.stories.tsx
  client/src/components/Chatting/ChatInput/index.tsx
  client/src/components/Chatting/index.tsx
Labels: frontend

#78 [FE/BE] 유저리스트 컴포넌트 "user/online" 소켓 연결
  client/src/components/Chatting/ChatInput/index.tsx
  client/src/components/Chatting/index.tsx
  client/src/components/RoomList/index.tsx
  client/src/components/UserList/UserTable/UserRecord/index.tsx
  client/src/components/UserList/index.stories.tsx
  client/src/components/UserList/index.tsx
  client/src/pages/landing/index.tsx
  client/src/pages/lobby/index.tsx
  client/src/pages/waiting/index.tsx
  server/src/app.gateway.ts
Labels: frontend, backend
