Repository boostcampwm-2022/web36-Japari, pull requests merged in 2022-12, with the labels that each got.

#85 [BE] 코드 보수 작업
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/prisma/migrations/20221202172626_/migration.sql
  server/prisma/migrations/20221202172901_/migration.sql
  server/prisma/schema.prisma
  server/src/@types/express.d.ts
  server/src/app.gateway.ts
  server/src/app.module.ts
  server/src/constants/config.ts
  server/src/constants/exception.ts
  server/src/constants/jwt-error.ts
  server/src/exception-filters/websocket.filter.ts
  server/src/main.ts
  server/src/modules/auth/auth.controller.ts
  server/src/modules/auth/auth.module.ts
  server/src/modules/auth/auth.service.ts
  server/src/modules/auth/github.service.ts
  server/src/modules/auth/jwt/jwt.guard.ts
  server/src/modules/auth/jwt/jwt.module.ts
  server/src/modules/auth/jwt/jwt.service.ts
  server/src/modules/chat/chat.gateway.ts
  server/src/modules/chat/chat.module.ts
  server/src/modules/game-room/game-room.controller.ts
  server/src/modules/game-room/game-room.gateway.ts
  server/src/modules/game-room/game-room.service.ts
  server/src/modules/game/game.module.ts
  server/src/modules/game/game.service.ts
  server/src/modules/jwt/jwt-access-token.guard.ts
  server/src/modules/jwt/jwt-access-token.strategy.ts
  server/src/modules/jwt/jwt-refresh-token.guard.ts
  server/src/modules/jwt/jwt-refresh-token.strategy.ts
  server/src/modules/jwt/jwt.module.ts
  server/src/modules/redis/redis.module.ts
  server/src/modules/redis/redis.service.ts
  server/src/modules/user/user.controller.ts
  server/src/modules/user/user.gateway.ts
  server/src/modules/user/user.module.ts
  server/tsconfig.json
Labels: backend

#88 [FE/BE] 닉네임 설정 및 유저 목록 버그 수정
  client/src/components/Modal/NickNameSetting/index.tsx
  server/src/app.gateway.ts
  server/src/modules/user/user.service.ts
Labels: bug, frontend, backend

#93 [FE / BE] mediasoup를 사용한 화상 / 음성 대화 구현
  .github/workflows/main.yml
  client/.gitignore
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/components/Audio/index.tsx
  client/src/components/Cam/index.stories.tsx
  client/src/components/Cam/index.tsx
  client/src/components/Header/StatusMedia/index.stories.tsx
  client/src/components/Header/StatusMedia/index.tsx
  client/src/components/Header/StatusMedia/styles.ts
  client/src/components/Header/StatusMicCam/index.tsx
  client/src/components/Header/index.tsx
  client/src/components/InGameCamList/index.stories.tsx
  client/src/components/InGameCamList/index.tsx
  client/src/components/Select/index.tsx
  client/src/components/WaitingRoomInfo/index.stories.tsx
  client/src/components/WaitingRoomInfo/index.tsx
  client/src/hooks/useCams.ts
  client/src/pages/playing/index.tsx
  client/src/pages/waiting/index.tsx
  client/src/setupProxy.js
  client/src/store/media.ts
  package-lock.json
  package.json
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/constants/config.ts
  server/src/main.ts
  server/src/modules/media/media.gateway.ts
  server/src/modules/media/media.module.ts
Labels: frontend, backend

#99 [FE / BE] 구글 로그인 구현
  server/src/constants/config.ts
  server/src/modules/auth/auth.module.ts
  server/src/modules/auth/auth.service.ts
  server/src/modules/auth/github.service.ts
  server/src/modules/auth/google.service.ts
Labels: frontend, backend

#104 [FE/BE] 정답이 헤더가 아닌 캔버스에 표시되도록 변경
  client/src/components/Game/CatchMind/index.tsx
  server/src/modules/redis/redis.module.ts
Labels: frontend

#100 [FE] 유저 목록 불러오기 스피너 적용 및 더미데이터 제거
  client/src/components/UserList/UserTable/index.tsx
  client/src/components/UserList/UserTable/styles.ts
  client/src/components/UserList/index.tsx
  client/src/components/UserList/styles.ts
  client/src/pages/dummy.ts
  client/src/pages/waiting/index.tsx
Labels: frontend

#102 [FE] 타이틀 및 아이콘 변경
  client/public/favicon.ico
  client/public/index.html
  client/public/logo.png
Labels: frontend

#109 [BE] 로비에서 게임 중인 방은 게임 목록에 표시되지 않도록 변경
  server/src/modules/game-room/game-room.gateway.ts
Labels: backend

#107 [BE] 그림을 그릴 사람이 방에 입장한 순서대로 결정되도록 변경
  client/src/components/Game/CatchMind/index.tsx
  server/src/app.gateway.ts
  server/src/modules/game-room/game-room.filter.ts
  server/src/modules/media/media.gateway.ts
  server/src/modules/play/catch-mind.gateway.ts
  server/src/modules/play/catch-mind.service.ts
Labels: backend

#113 [FE / BE] 인게임 페이지에서 새로고침, 뒤로 가기 등에 대한 처리
  client/src/components/InGameComponent/index.tsx
  client/src/components/InGameComponent/styles.tsx
  client/src/components/WaitingRoomInfo/index.tsx
  client/src/pages/playing/index.tsx
  client/src/pages/playing/styles.ts
  client/src/pages/waiting/index.tsx
  server/src/app.gateway.ts
  server/src/main.ts
  server/src/modules/play/catch-mind.gateway.ts
Labels: frontend, backend

#117 [FE / BE] 캐치마인드 기능 개선
  client/src/@types/image.d.ts
  client/src/assets/icons/palette-lock.png
  client/src/assets/images/leather-background.webp
  client/src/assets/images/oak-texture-background.webp
  client/src/components/Game/CatchMind/index.tsx
  client/src/components/Game/CatchMind/styles.ts
  client/src/components/Game/index.tsx
  client/src/components/InGameComponent/index.tsx
  client/src/components/RoomList/index.tsx
  server/src/modules/play/catch-mind.gateway.ts
  server/src/modules/play/catch-mind.service.ts
Labels: bug, enhancement, frontend, backend

#118 [FE] 유저 점수 상태관리 및 실시간 점수 표시
  client/src/components/Cam/index.tsx
  client/src/components/Cam/styles.ts
  client/src/components/Game/CatchMind/index.tsx
  client/src/store/catchmind.ts
  server/src/modules/play/catch-mind.service.ts
Labels: frontend

#119 [FE] 캔버스 펜 두께 설정, 지우개 모드 관련 버그 해결
  client/src/components/Game/CatchMind/index.tsx
  server/src/modules/media/media.gateway.ts
Labels: bug, frontend

#124 [BE] 그림을 그리는 사람이 게임에서 나갈시 다음 라운드로 넘어가도록 수정
  server/src/@types/catch-mind.d.ts
  server/src/modules/play/catch-mind.gateway.ts
  server/src/modules/play/catch-mind.service.ts
Labels: bug, backend

#132 [FE] 게임 시작 시 최소 인원 수 확인하도록 변경
  client/src/components/RoomList/index.stories.tsx
  client/src/components/RoomList/index.tsx
  client/src/components/WaitingRoomInfo/index.stories.tsx
  client/src/components/WaitingRoomInfo/index.tsx
Labels: frontend

#130 [FE] eslint warning 해결, 오타 수정, 주석 제거
  client/src/components/Game/CatchMind/index.tsx
  client/src/components/Game/CatchMind/styles.ts
  client/src/components/WaitingRoomInfo/index.tsx
  client/src/pages/playing/index.tsx
  client/src/pages/waiting/index.tsx
Labels: invalid, frontend

#128 [BE] 이미 시작한 방에 입장 시 join-failed 처리
  server/src/modules/game-room/game-room.gateway.ts
Labels: backend

#126 [FE/BE] 그림을 그리는 사람이 종료했을 때의 처리 개선
  client/src/components/Header/index.tsx
  server/src/app.gateway.ts
  server/src/modules/game-room/game-room.gateway.ts
  server/src/modules/play/catch-mind.gateway.ts
  server/src/modules/play/catch-mind.service.ts
  server/src/modules/play/play.module.ts
Labels: bug, frontend, backend

#136 [BE] media.gateway.ts 리팩토링
  client/src/components/Game/CatchMind/index.tsx
  client/src/components/WaitingRoomInfo/index.tsx
  server/src/modules/media/media.gateway.ts
Labels: backend

#137 [BE] 특정 시나리오에서 발생하는 버그 해결
  server/src/modules/play/catch-mind.service.ts
Labels: bug, backend

#139 [FE / BE] 화상/음성 장치가 없는 사용자에 대한 처리
  client/src/hooks/useCams.ts
  server/src/modules/media/media.gateway.ts
Labels: frontend, backend

#141 [FE] 랜딩 페이지 수정, Page 컴포넌트 min-width 설정
  client/src/assets/images/landing-background-image.png
  client/src/assets/images/landing-image.png
  client/src/assets/images/playing-example.png
  client/src/assets/images/waiting-example.png
  client/src/assets/images/white-paint.png
  client/src/components/Page/styles.ts
  client/src/pages/landing/index.tsx
  client/src/pages/landing/styles.ts
Labels: frontend

#145 [FE / BE] 랭킹 관련 기능 추가
  client/src/api/user.ts
  client/src/components/Profile/ProfileContent/index.tsx
  client/src/components/Profile/ProfileContent/styles.ts
  client/src/components/UserList/UserListTab/styles.ts
  client/src/components/UserList/index.tsx
  server/src/modules/user/user.controller.ts
  server/src/modules/user/user.service.ts
Labels: frontend, backend

#149 Feature/cam show mike on off
  client/src/components/Button/styles.ts
  client/src/components/Cam/index.tsx
  client/src/components/Header/StatusMedia/index.tsx
  client/src/components/InGameCamList/index.tsx
  client/src/components/WaitingRoomInfo/index.tsx
  client/src/components/WaitingRoomInfo/styles.ts
  server/src/modules/media/media.gateway.ts
Labels: frontend

#148 [FE] select에서 battleship을 선택할 수 없도록 수정
  client/src/components/Select/index.tsx
Labels: frontend

#152 [FE] 뷰 포트에 맞추어 html font-size 지정, 컴포넌트 사이즈 조정
  client/src/components/Button/styles.ts
  client/src/components/Cam/styles.ts
  client/src/components/Chatting/ChatInput/index.tsx
  client/src/components/Chatting/ChatInput/styles.ts
  client/src/components/Chatting/ChatLog/styles.ts
  client/src/components/Chatting/styles.ts
  client/src/components/Game/CatchMind/index.tsx
  client/src/components/Game/CatchMind/styles.ts
  client/src/components/Header/Logout/index.tsx
  client/src/components/Header/Logout/styles.ts
  client/src/components/Header/StatusMedia/index.tsx
  client/src/components/Header/StatusMedia/styles.ts
  client/src/components/Header/styles.ts
  client/src/components/InGameCamList/styles.ts
  client/src/components/InGameComponent/styles.tsx
  client/src/components/Logo/index.tsx
  client/src/components/Logo/styles.ts
  client/src/components/Profile/styles.ts
  client/src/components/RoomList/RoomRecord/styles.ts
  client/src/components/RoomList/styles.ts
  client/src/components/UserList/styles.ts
  client/src/components/WaitingRoomInfo/styles.ts
  client/src/pages/lobby/styles.ts
  client/src/styles/global.ts
Labels: frontend

#155 [FE / BE] 마이너 버그 픽스
  client/src/components/Chatting/ChatLog/index.tsx
  client/src/components/Chatting/ChatLog/styles.ts
  client/src/components/Game/CatchMind/index.tsx
  client/src/components/WaitingRoomInfo/index.tsx
  client/src/pages/waiting/index.tsx
  server/src/modules/play/catch-mind.service.ts
Labels: bug, frontend, backend

#157 [FE] 방이 없을 때 텍스트 표시
  client/src/components/RoomList/index.tsx
  client/src/components/RoomList/styles.ts
  client/src/components/WaitingRoomInfo/index.tsx
Labels: frontend

#153 [FE] 마이크 / 카메라 온오프 시 렌더링
  client/src/components/InGameCamList/index.tsx
  client/src/components/InGameCamList/styles.ts
  client/src/components/InGameComponent/index.tsx
  client/src/components/WaitingRoomInfo/index.tsx
  client/src/pages/waiting/index.tsx
Labels: frontend

#159 [FE/BE] 게임 도중 인원이 최소 인원 수 미만이 되면 즉시 게임을 종료
  client/src/components/Game/CatchMind/index.tsx
  client/src/components/Game/CatchMind/styles.ts
  server/src/modules/play/catch-mind.gateway.ts
  server/src/modules/play/catch-mind.service.ts
Labels: frontend, backend

#163 Release v1.0.5
  client/src/components/Game/CatchMind/index.tsx
Labels: release

#165 Release v1.0.6
  client/src/components/Game/CatchMind/index.tsx
  client/src/components/WaitingRoomInfo/styles.ts
Labels: release
